version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      args:
        - DEV=true
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  frontend:
    build: 
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    build:
      context: ./nginx
    ports:
    - 3000:3000
    - 3101:3101