version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app